### ISSUE TITLE
exact search

### ISSUE THREAD

**Issue by xin-jin** [camlspotter/ocamloscope#20]
Are there any search tricks? I am not sure how the search engine matches strings, but when I search, say `factor`, there are a lot of results I don't want (like `actor`, `filter`). Is it possible to do exact match?

Also sometimes the search results are not complete. For example, if I search `gcd`, it cannot find `gcd_big_int`.

**Comment by camlspotter** [comment]
Names are matached using Levenshtein edit distance, but it had two issues:

* The edit distance of names were not considered in the final search result score.
* The edit distance match itself seems not very useful for the name match.

In the upcoming OCamlOScope 4.02.1, name matches are done simple substring match, which should have better results.

**Comment by camlspotter** [comment]
OCamlOScope is now ported to 4.02.1 and its name search becomes simple substring match.
