### ISSUE TITLE
'src' links all broken?

### ISSUE THREAD

**Issue by jseakle** [camlspotter/ocamloscope#23]
Hi! I don't know much about this project, and was just linked to it from #ocaml on freenode. It seems from here that all the 'src' links go to a plain html page with a single line of text reading "<long file name> does not exist locally."

**Comment by camlspotter** [comment]
Thanks for the report. SRC links are dead since we are at the transition period from OCamlOScope based on OCaml 4.01.0 to 4.02.1. Now it should look better: if there is no corresponding local source available in the search engine, the SRC link is not displayed.
